### ISSUE TITLE
Reduce logging verbosity 

### ISSUE THREAD

**Issue by janengelmohr** [visi0nary/android_device_alps_k05ts_a#10]
I/O is slow so once everything works, reduce mediatek logcat spamming

**Comment by janengelmohr** [comment]
Especially the fingerprint libraries spam like hell thus slowing down the whole device!

**Comment by janengelmohr** [comment]
No more fingerprint spam! https://github.com/visi0nary/android_vendor_elephone_p8000/commit/8ae4d9ba7936ee589e368611567c20cf179065ad This makes the unlocking UI much more fluid :+1:

**Comment by janengelmohr** [comment]
Memtrack was removed, UI is more fluid and we have less spamming https://github.com/visi0nary/android_vendor_elephone_p8000/commit/7e81f1723caf94b0de11e086054e9bcdc278499e

**Comment by janengelmohr** [comment]
Still spamming:
- auditd
- wpa_supplicant
- SLCODE (a bit, hard to fix in prebuilt lib though)
- thermal_repeater
- lights
- ccci_fsd

**Comment by walter79** [comment]
audit is fixable, audit binary is missing in /system/bin.  For lights, ccci .... we should try files from zopo or a different device.

**Comment by janengelmohr** [comment]
I was thinking about piping output to /dev/null

**Comment by janengelmohr** [comment]
Logs are silent enough now I guess
