### ISSUE TITLE
Titanium Backup crashes

### ISSUE THREAD

**Issue by janengelmohr** [visi0nary/android_device_alps_k05ts_a#11]
See [this user report](forum.xda-developers.com/showpost.php?p=65588773&postcount=196).

Is it reproducable?

**Comment by micbanand** [comment]
I was wrong. sorry

**Comment by micbanand** [comment]
oh long shot. did a reinstall because  open gapps then gapps from thread. keept making crashes

**Comment by walter79** [comment]
Worked well. Use CGApps  https://github.com/cgapps/vendor_google/blob/builds/README.md

**Comment by janengelmohr** [comment]
Worked for me too.
