### ISSUE TITLE
"Backup and Restore" in settings crashes settings.apk

### ISSUE THREAD

**Issue by janengelmohr** [visi0nary/android_device_alps_k05ts_a#15]

**Comment by janengelmohr** [comment]
Logcat: 
E/AndroidRuntime( 2582): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.SubSettings}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.app.backup.IBackupManager.isBackupServiceActive(int)' on a null object reference
E/AndroidRuntime( 2582):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
E/AndroidRuntime( 2582):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
E/AndroidRuntime( 2582):    at android.app.ActivityThread.access$900(ActivityThread.java:154)
E/AndroidRuntime( 2582):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
E/AndroidRuntime( 2582):    at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 2582):    at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 2582):    at android.app.ActivityThread.main(ActivityThread.java:5294)
E/AndroidRuntime( 2582):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2582):    at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 2582):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime( 2582):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime( 2582): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.app.backup.IBackupManager.isBackupServiceActive(int)' on a null object reference
E/AndroidRuntime( 2582):    at com.android.settings.PrivacySettings.getNonVisibleKeys(PrivacySettings.java:320)
E/AndroidRuntime( 2582):    at com.android.settings.PrivacySettings.onCreate(PrivacySettings.java:102)
E/AndroidRuntime( 2582):    at android.app.Fragment.performCreate(Fragment.java:2031)
E/AndroidRuntime( 2582):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:863)
E/AndroidRuntime( 2582):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
E/AndroidRuntime( 2582):    at android.app.BackStackRecord.run(BackStackRecord.java:834)
E/AndroidRuntime( 2582):    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1452)
E/AndroidRuntime( 2582):    at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:483)
E/AndroidRuntime( 2582):    at com.android.settings.SettingsActivity.switchToFragment(SettingsActivity.java:1000)
E/AndroidRuntime( 2582):    at com.android.settings.SettingsActivity.onCreate(SettingsActivity.java:603)
E/AndroidRuntime( 2582):    at android.app.Activity.performCreate(Activity.java:5990)
E/AndroidRuntime( 2582):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime( 2582):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
E/AndroidRuntime( 2582):    ... 10 more

**Comment by walter79** [comment]
fixed with https://github.com/visi0nary/android_device_elephone_p8000/commit/fa1da57391d4ccf26e1ec64edafb39e80b4380cd
