### ISSUE TITLE
Night Mode is not hardware accelerated

### ISSUE THREAD

**Issue by janengelmohr** [visi0nary/android_device_alps_k05ts_a#17]
When switching on night mode the device begins to lagg...

**Comment by janengelmohr** [comment]
https://github.com/kushan02/android_device_samsung_jf-common/blob/cm-13.0/BoardConfigCommon.mk#L80 Looks like we have to compile hwcomposer from source and patch it. Luckily we have ZOPO's sources so this should be possible

**Comment by janengelmohr** [comment]
There are apps as workaround so #wontfix

**Comment by valascus** [comment]
I guess u could chante that hashtag :smile: 
#fixed
