### ISSUE TITLE
Some apps like WhatsApp are "not compatible with the device"

### ISSUE THREAD

**Issue by janengelmohr** [visi0nary/android_device_alps_k05ts_a#20]

**Comment by davidep** [comment]
It happened to me for a not important application only, How to Tie a Tie.
I couldn't even restore it via TB
Although I was able to restore Whatsapp via TB and it is working fine.

**Comment by micbanand** [comment]
Could restore aliexpress via TB
Works fine! Now it ask for update. Goes to gplay and tells not supported

**Comment by walter79** [comment]
fixed with 
https://github.com/visi0nary/android_device_elephone_p8000/commit/fa1da57391d4ccf26e1ec64edafb39e80b4380cd
