### ISSUE TITLE
There is no "National Roaming" option as usual for CM

### ISSUE THREAD

**Issue by davidep** [visi0nary/android_device_alps_k05ts_a#22]
The option "National Roaming" is missing, this is very useful in particular when the own provider is a MVNO...
This is usually an additional option in CM based ROM below "Data Roaming"

https://www.reddit.com/r/Android/comments/22c82e/roaming_at_home_on_android_why_some_networks_need/ it basically allow Roaming within the home country.

**Comment by janengelmohr** [comment]
Thanks for reporting!

**Comment by ChatSim** [comment]
Do you want to save on roaming costs while travelling all around the world? Try ChatSim! ChatSim is the first SIM that lets you exchange unlimited instant messages and emoji, in more than 150 countries, using the most popular instant messaging apps, for only 10 euros/year, even without a WiFi connection. ChatSim can connect to the roaming operators, without charging in roaming. It can connect to more than 400 roaming operators. You can use: WhatsApp, Facebook Messenger, WeChat, Telegram, BBM, Line, Kik, Hike, Kakao, and QQi. ChatSim also works with 4G technology and has an automatic firewall that is able to block unwanted data traffic up to 90%. If you want to know more about ChatSim Unlimited, visit our website: chatsim.com/en

**Comment by kezmdor** [comment]
Looks to me as this option was removed in CM11.  National data roaming is now configured on network basis.
https://jira.cyanogenmod.org/plugins/servlet/mobile#issue/CYAN-2952

**Comment by kezmdor** [comment]
@visi0nary this issue should be closed. As I described above this option is no longer available in CM. A change request I opened regarding national roaming between O2 and former E-Plus networks is currently in review at Cyanogenmod: http://review.cyanogenmod.org/#/c/135751/
Don't know how long the review process will take, but I would love to see this patch in the next release of CM for P8000 since I am a O2 user. ;)
https://github.com/CyanogenMod/android_frameworks_base/commit/dab7d659a7bdc0c2d2c89630fce884e9bebabac4

**Comment by janengelmohr** [comment]
Good finding @kezmdor! As far as I understood I would have to define national roaming for each and every country... Are there some prebuilt lists for this maybe? I'm also using Simyo which is O2/EPlus, so your commit definitely helps here ;)

**Comment by kezmdor** [comment]
@visi0nary, long ago I described this at xda: http://forum.xda-developers.com/elephone-p8000/development/mod-remove-roaming-home-network-t3206004
You need to know which networks within a country, or even from different countries can be used for data without roaming costs.
You can find the MCC (mobile country code) and MNC (mobile network code) number for example here: http://mcclist.com/mobile-network-codes-country-codes.asp. But in the end you need the help of the community to get a full list of valid non roaming networks.

**Comment by davidep** [comment]
Nice finding @kezmdor, according to the operational provider listed in http://mcclist.com/mobile-network-codes-country-codes.asp#G
O2 shouldn't be specified also for MNC 08?

Just wondering as my default is Eplus on 26203 and I'm wondering if all the O2 operational MNC needs to be included.

I had this issue also on Eragon ROM but skeleton couldn't fix the issue via the framework workaround by just giving him my current MCC and MNC.

**Comment by janengelmohr** [comment]
Closed because it doesn't exist anymore. I'll implement some common MCCs though. Thanks for the help!

**Comment by janengelmohr** [comment]
EPlus/O2 use national roaming as well and that R symbol annoys me...

**Comment by janengelmohr** [comment]
fixed with 6163c263758b12bbf7009930720303eccecd172c
