### ISSUE TITLE
MTP and USB data issue

### ISSUE THREAD

**Issue by davidep** [visi0nary/android_device_alps_k05ts_a#24]
The first time I plugged an USB cable to my PC the device was not recognized, neither mounted.
I could only see the USBdebugger icon on the device, but no option to switch mode.

I did installed USB Mass storage Enabler app, but now with MTP mode on, 
I can only see the icon related to the device, but I cannot mount/browse any data on it.

In MassStorage mode, it doesn't show anything.

**Comment by janengelmohr** [comment]
Thanks for reporting this issue! MTP is fixed with 67be7586404e0dc88ceb78278d4b26d45497a5b0. I'll look into Mass Storage later as it isn't that of a high priority.
