### ISSUE TITLE
Android Auto not working

### ISSUE THREAD

**Issue by davidep** [visi0nary/android_device_alps_k05ts_a#26]
This was not working well also on the stock and eragon ROM, but here it doesn't start at all and the car infotainment can't establish a connection. 
The car can see the device plugged but can't establish any data connection.

**Comment by janengelmohr** [comment]
If it works through Bluetooth, then I know the problem: Audio Over Bluetooth ist still broken. I already have a fix that I'll push once I release a new version. Thanks for reporting, please let me know if the new version I'll release in the upcoming days works. :+1:

**Comment by davidep** [comment]
FingerCrossed then :) 
Even if Android Auto requires a cable connection, bluetooth might be involved as well, so let's see...
I'll test the new build and let you know. 
Thanks ;)

**Comment by janengelmohr** [comment]
I don't own a car that supports Android Auto (it's a 1990' VW Polo, haha). Could you test if it works in the latest build?

**Comment by davidep** [comment]
Haha, I tested it again with build n.4 and 4.2 and unfortunately it is still not working.
The Bluetooth connection works fine though.

**Comment by davidep** [comment]
Below the logcat right after the phone was plugged and AndroidAuto executed.
[2016-03-14-13-35-28.txt](https://github.com/visi0nary/android_device_elephone_p8000/files/172169/2016-03-14-13-35-28.txt)

As with the stock ROM the phone show the AndroidAuto logo in white on the black background, and the car's screen shows just a black screen.

**Comment by walter79** [comment]
Maybe some permissions missing.

https://github.com/TeamExodus/frameworks_base/commit/9c36be651e83fb039a262682839bd920b033007a

**Comment by davidep** [comment]
New logs attached  for test with build cm-12.1-20160317-UNOFFICIAL-p8000.zip by @walter79 

```
03-20 17:33:19.199 D/ConnectivityManager.CallbackHandler(7843): CM callback handler got msg 524295
..
03-20 17:33:33.077 I/VirtualDisplayAdapter(746): Virtual display device released because application token died: com.google.android.gms
03-20 17:33:33.081 D/GraphicBuffer(258): unregister, handle(0x7fa180e520) (w:1 h:1 s:16 f:0x1 u:0x000300)
03-20 17:33:33.082 W/libEGL  (258): EGLNativeWindowType 0x7fa91f5c10 disconnect failed
03-20 17:33:33.091 W/VirtualDisplayAdapter(746): Failed to notify listener of virtual display event.
03-20 17:33:33.091 W/VirtualDisplayAdapter(746): android.os.DeadObjectException
03-20 17:33:33.091 W/VirtualDisplayAdapter(746):    at android.os.BinderProxy.transactNative(Native Method)
03-20 17:33:33.091 W/VirtualDisplayAdapter(746):    at android.os.BinderProxy.transact(Binder.java:496)
03-20 17:33:33.091 W/VirtualDisplayAdapter(746):    at android.hardware.display.IVirtualDisplayCallback$Stub$Proxy.onStopped(IVirtualDisplayCallback.java:125)
03-20 17:33:33.091 W/VirtualDisplayAdapter(746):    at com.android.server.display.VirtualDisplayAdapter$Callback.handleMessage(VirtualDisplayAdapter.java:364)
03-20 17:33:33.091 W/VirtualDisplayAdapter(746):    at android.os.Handler.dispatchMessage(Handler.java:102)
03-20 17:33:33.091 W/VirtualDisplayAdapter(746):    at android.os.Looper.loop(Looper.java:135)
03-20 17:33:33.091 W/VirtualDisplayAdapter(746):    at android.os.HandlerThread.run(HandlerThread.java:61)
03-20 17:33:33.091 W/VirtualDisplayAdapter(746):    at com.android.server.ServiceThread.run(ServiceThread.java:46)
03-20 17:33:33.092 I/DisplayManagerService(746): Display device removed: DisplayDeviceInfo{"Dummy": uniqueId="virtual:com.google.android.gms,10020,Dummy,0", 1 x 1, 60.0 fps, supportedRefreshRates [60.0], density 130, 130.0 x 130.0 dpi, appVsyncOff 0, presDeadline 16666666, touch NONE, rotation 0, type VIRTUAL, state ON, owner com.google.android.gms (uid 10020), FLAG_PRIVATE, FLAG_NEVER_BLANK, FLAG_PRESENTATION, FLAG_OWN_CONTENT_ONLY}
03-20 17:33:33.093 V/ActivityManager(746): Display removed displayId=7
03-20 17:33:33.094 E/JavaBinder(746): !!! FAILED BINDER TRANSACTION !!!
```

[2016-03-20-17-33-42.txt](https://github.com/visi0nary/android_device_elephone_p8000/files/181965/2016-03-20-17-33-42.txt)

**Comment by davidep** [comment]
This seems to be fixed now, after installing manually Android Auto 1.6.226040 (2710411-release)
http://forum.xda-developers.com/showpost.php?p=66106954&postcount=11

**Comment by janengelmohr** [comment]
I also just saw it. Can you confirm that it is working now?

**Comment by davidep** [comment]
Yep, I tested it with build #6 and it worked like a charm :)

**Comment by janengelmohr** [comment]
Great, I will update the CM post accordingly. Thank you for the investigation!
