### ISSUE TITLE
signal and google play 

### ISSUE THREAD

**Issue by coolabah** [visi0nary/android_device_alps_k05ts_a#29]
Keeps saying mobile network is blocked and mobile data is blocked and my signal drops and has no bars and google play is having problems won't let me install certain apps and stops responding sometimes

**Comment by janengelmohr** [comment]
Mobile data was fixed with this commit: https://github.com/visi0nary/framework_opt_telephony_mt6753/commit/0dc0bbfb8745788ee9e651dc22f4300d09c571c3

Sorry but I can't reproduce the issue. Thanks for reporting though!

**Comment by janengelmohr** [comment]
Google Play issues are already known, see issue #20
