### ISSUE TITLE
Support Smartcover

### ISSUE THREAD

**Issue by janengelmohr** [visi0nary/android_device_alps_k05ts_a#33]

**Comment by walter79** [comment]
Maybe we should try this:

https://github.com/fire855/android_packages_apps_SmartCover-mtk

**Comment by janengelmohr** [comment]
Tested and does not seem to work. I found some framework code snippets though which I will test out

**Comment by janengelmohr** [comment]
CM 12.1 won't get any new features, so #wontfix
