### ISSUE TITLE
Add Engineer Mode

### ISSUE THREAD

**Issue by janengelmohr** [visi0nary/android_device_alps_k05ts_a#39]
Sound output is rather low. Check if it can be increased somehow

**Comment by divis1969** [comment]
It looks like MTK-specific audio volume is implemented in the following way:
1. Some data is loaded from NV (I've seen the same attempt to load this data from enginnering app):
   https://github.com/xen0n/android_hardware_mediatek/blob/8e86c4e63154b0b1d724f6405655672422d3985d/common/audio/V2/AudioMTKPolicyManager.cpp#L5195
2. These data is applied via
   https://github.com/xen0n/android_hardware_mediatek/blob/8e86c4e63154b0b1d724f6405655672422d3985d/common/audio/V2/AudioMTKPolicyManager.cpp#L5092

The code is not complete (and I maybe wrong about it) but could give some clue...

**Comment by janengelmohr** [comment]
Good finding, thanks! I will check it out.

**Comment by janengelmohr** [comment]
This (https://github.com/visi0nary/android_device_elephone_p8000/commit/04da9dbeb51bb0b4cfd5760ebaea8b143c6c2050) works if both files are **manually** copied to /nvdata like it is done in the script. For some reason the script will only copy the AUXADC file though and leave the other untouched...

Essentially these two files are needed to get louder audio. I just flashed stock, changed volume parameters there and extracted the files from nvram ;)

**Comment by divis1969** [comment]
it's a little bit weird. I supposed these files are not changed by user and thus should not be modified between stock and CM re-flashing.
Does your port uses audio policy manager from stock or it is built from sources (frameworks/av)

**Comment by janengelmohr** [comment]
It is built from stock of course ;)

**Comment by janengelmohr** [comment]
Fixed with https://github.com/visi0nary/android_device_elephone_p8000/commit/d543f2dcde22342e3242ce97169b0e4cdc427bad thank you very much for support @divis1969!
