### ISSUE TITLE
Fingerprint doesn't work 

### ISSUE THREAD

**Issue by janengelmohr** [visi0nary/android_device_alps_k05ts_a#4]
Should be possible to get it working without modifying CM source since CM supports it natively but who knows what Silead did there...

**Comment by janengelmohr** [comment]
Are framework changes needed for FP to work?

**Comment by micbanand** [comment]
did google and it seems like people optimize with framework 
did see some with problems with hardware ID mismatch
Long shot. but maybe?

**Comment by visi0nary** [comment]
Merging framework code from ZOPO should be sufficient.

**Comment by janengelmohr** [comment]
Merging Silead framework code from ZOPO should be sufficient.

**Comment by janengelmohr** [comment]
Looks like we need to build our own HAL as Silead implemented the FP via an app which is not a real option for me. HALs are there for a reason :smile:

**Comment by oezgan** [comment]
This is an android app ? Can we somehow reverse engineer it ?

**Comment by janengelmohr** [comment]
Funny that you mention it right now. I just got it fully working in this exact moment! :dancers: Still testing some things out though ;)

**Comment by janengelmohr** [comment]
Fixed with 14711b5 7492d37 55b4d5c a9b7261 ec2b478

**Comment by janengelmohr** [comment]
Still no HAL implementation but it's a start. At least it works with SILEAD's custom implementation ;)

**Comment by oezgan** [comment]
Will try to reverse engineer it :) when i find the chance :+1:
