### ISSUE TITLE
External storage broken in Build #4

### ISSUE THREAD

**Issue by janengelmohr** [visi0nary/android_device_alps_k05ts_a#42]
http://zidroid.com/how-to-fix-extsdcard-mount-issue-on-kitkat-and-lollipop/

Make build chain generate platform.xml instead of copying it

**Comment by janengelmohr** [comment]
Maybe also related to #37

**Comment by walter79** [comment]
https://github.com/visi0nary/android_device_elephone_p8000/blob/cm-12.1/device_p8000.mk#L61

We can remove this line. (but first a test)

**Comment by janengelmohr** [comment]
Exactly ;)

**Comment by janengelmohr** [comment]
Fixed with 342c27c353b4221c3da3f0804b7e973caa05d2c1
