### ISSUE TITLE
weather widget

### ISSUE THREAD

**Issue by oezgan** [visi0nary/android_device_alps_k05ts_a#45]
Weather Widget below the status bar is not shown... Probably small issue but... a bug is a bug :)

**Comment by janengelmohr** [comment]
Thanks for the report! Works for me though on build 4, do you mean this weather widget? http://i.imgur.com/iSKP9kZ.jpg

**Comment by oezgan** [comment]
Oh yes Sorry, from my old Samsung S4 i was used to have a widget below the quick settings icons now it is there, sorry no bug :+1:

**Comment by janengelmohr** [comment]
No problem and thanks for participating :)
