### ISSUE TITLE
Patches

### ISSUE THREAD

**Issue by Preet23** [visi0nary/android_device_alps_k05ts_a#49]
How do you apply the patches and where to apply them? I ran the script in root of a cm based ROM but it didn't worked saying that the directory doesn't exists.

**Comment by janengelmohr** [comment]
cd into the patches folder and apply them from there with ./apply-patches.sh

**Comment by Preet23** [comment]
Where to place it? I tried that already, no luck.

**Comment by janengelmohr** [comment]
You don't have to place them anywhere. As I said go to device/elephone/p8000/patches and run ./apply-patches.sh. That's it! ;) You might need to add x permissions to that shell script before.

**Comment by Preet23** [comment]
Which permissions to add?
And are these patches mediatek wide? Because I am also going to add these patches in mt6589 device  :D

**Comment by nachfuellbar** [comment]
@Preet23 `chmod +x apply-patches.sh`

or just `sh apply-patches.sh` to execute without adding execution permission

**Comment by Preet23** [comment]
Thanks @nachfuellbar, I actually figured it out before :3
