### ISSUE TITLE
Wifi lost connection during standby

### ISSUE THREAD

**Issue by walter79** [visi0nary/android_device_alps_k05ts_a#50]
Fix: update vendor files (use Zopo Speed 7 files)

/system/etc/wifi 
- p2p_supplicant_overlay.conf
- wpa_supplicant.conf
- wpa_supplicant_overlay.conf

**Comment by walter79** [comment]
Works only sometimes.

**Comment by janengelmohr** [comment]
Fixed with a2ecdea796dfb0da4831e6805d513275a3eecb8d and 24d9f8ac91b5431271652587da19d589adf6b060

**Comment by janengelmohr** [comment]
Still not fully fixed...

**Comment by janengelmohr** [comment]
According to mkoas, it is because "SETSUSPENDMODE 1" is always issued regardless of what is set in OS level. This only happens when the device is not connected to any power sources (thus making the bug harder to spot without ADB).

**Comment by oezgan** [comment]
Is this an issue related to the wpa_supplicant ? The version used here is fairly old 0.8 vs 2.5 may be using the newest version could help ?

**Comment by janengelmohr** [comment]
Seems to be, yes. Stock wpa_supplicant is somewhat different - have you maybe checked its version?

**Comment by oezgan** [comment]
Yes Stock WPA Supplicant is 2.3 newest version is 2.5 , but from what i see is that the "SETSUSPENDMODE 1" is issued by the system, kernel may be ?  not the wpa_supplicant

**Comment by janengelmohr** [comment]
Fixed with https://github.com/visi0nary/android_vendor_elephone_p8000/commit/e0626c49c40b8bc004e7a3ea87f5c9e30a6aa83a
