### ISSUE TITLE
Fix battery drain

### ISSUE THREAD

**Issue by janengelmohr** [visi0nary/android_device_alps_k05ts_a#58]
I am pretty sure this is caused by the Fingerprint.

**Comment by janengelmohr** [comment]
Can someone confirm that the battery runtime got worse from build 5 to 6/7?

**Comment by janengelmohr** [comment]
Fixed with build 7.1

**Comment by janengelmohr** [comment]
...not really. Many people report the battery usage is still higher than on stock. I observed that this is only when the screen is on, idle drain is fine. Neutral tests would be fine because the drain just "feels" faster as of now.

**Comment by ggogel** [comment]
Sometimes I get really high battery usage from Android OS and Mobile Network, it keeps the phone active(out of deepsleep) for hours. I couldn't find the reason, yet...[http://imgur.com/a/GHL9X](url)

**Comment by janengelmohr** [comment]
Can someone compare the run time to stock or stock-based ROMs?

**Comment by ggogel** [comment]
With the stock Tom it's definitely lower. This night Android OS again sucked my battery from about 50% to 15% in about 8h in idle/screen off.

**Comment by janengelmohr** [comment]
That is odd. Are you in a busy WiFi and is this regular behaviour? I will benchmark my battery as well soon.

**Comment by ggogel** [comment]
No I'm in my home WiFi. It only happens from time to time. Somehow Android OS hangs up and is just killing the battery, there has to be some event which triggers this. Maybe the fingerprint sensor. I've double tap to wake already disabled, so I can exclude that.

**Comment by janengelmohr** [comment]
If it was the FP sensor then it would happen on stock as well. Maybe the modem is going bonkers, who knows? Can you install Wakelock Detector and check wakelocks if it happens again?

**Comment by ggogel** [comment]
I've already checked that. It shows nothing suspicious or helpful, only that the phone was awake over 50% of the time and I didn't used it in this time or only for a few minutes. https://s31.postimg.org/3mweqyv3f/Screenshot_2016_06_06_04_35_41.png

**Comment by ggogel** [comment]
I installed the newest update and it seems to be fixed, at least for now...

**Comment by janengelmohr** [comment]
For the record: It indeed was the fingerprint scanner spamming logs over and over again keeping the phone busy with I/O every second.

**Comment by janengelmohr** [comment]
For the record: It indeed was the fingerprint scanner spamming logs over and over again keeping the phone busy with I/O every second.

**Comment by ggogel** [comment]
Thank you for reporting back. I installed the latest ota yesterday and was surprised that this issue has vanished entirely. Great work :)
