### ISSUE TITLE
Proximity sensor not working

### ISSUE THREAD

**Issue by desmoloch** [visi0nary/android_device_alps_k05ts_a#62]
On build #7 proximity sensor is not working. If I get a call, screen does not fade out.

**Comment by desmoloch** [comment]
Working with gueste Kernel.

**Comment by kezmdor** [comment]
Just updated from build #6 to #7 and proximity sensor works for me. Tested with an outgoing call, but I don't think this would change the thing.

**Comment by janengelmohr** [comment]
Just made a call and it worked fine. Looks like an issue with your setup.

**Comment by desmoloch** [comment]
Strange. I updated from #6 to #7, wiped cache and dalvik and installed xposed again. I will try to flash #7 again.

**Comment by desmoloch** [comment]
Flashed #7 over #7 again. Now proximity sensor is working. Very strange. Thanks for your response!
