### ISSUE TITLE
AudioFX not working

### ISSUE THREAD

**Issue by desmoloch** [visi0nary/android_device_alps_k05ts_a#63]
AudioFX does not work (tested at least Headset and loudspeaker).

**Comment by janengelmohr** [comment]
Thanks for the report! I just tried it via A2DP and Headset and it's definitely working here. I am on Build 7 now btw.

**Comment by desmoloch** [comment]
Very strange. Did not work for me with build #6 also, and I did a fullwipe before Installation. I just installed catlog on my build.#7, but there is no error for Audiofx. 
Anything i can do to determine why it does not work? Maybe it's related to xposed? Do you have xposed installed?

**Comment by janengelmohr** [comment]
Nope, I just CM as it is. Could be related to xposed though, yep! If there are no errors whatsoever in the logcat it is really strange...

**Comment by desmoloch** [comment]
Arrrrr i have to kill Amazon... I'm using Amazon music App. Audiofx does NOT work with Amazon music. Cause Amazon does not register the app as music player (cannot be used as default music App, music volume is not decreased while using runtastic AND Audiofx not working)
Tested Audiofx with Google Music: working! Sorry for the confusion.

**Comment by janengelmohr** [comment]
No problem, thanks for the report anyways!
