### ISSUE TITLE
App2SD is broken

### ISSUE THREAD

**Issue by janengelmohr** [visi0nary/android_device_alps_k05ts_a#64]
The OS reports there is not enough space on the external SD when trying to move apps onto it.

**Comment by walter79** [comment]
E/Vold    (  256): Error creating imagefile (Read-only file system)
E/Vold    (  256): ASEC image file creation failed (Read-only file system)
W/Vold    (  256): Returning OperationFailed - no handler for errno 30
D/SocketClient(  256): SocketClient sendData done: 400 11 asec operation failed (Read-only file system)
E/PackageHelper( 6449): Failed to create secure container smdl785866653.tmp
W/DefContainer( 6449): Failed to copy package at /data/app/de

**Comment by walter79** [comment]
fixed with [c0b4295](https://github.com/visi0nary/android_device_elephone_p8000/commit/a8dd1f81ac47fd05f67c9a6fe38e2bc40b0d760a)

**Comment by janengelmohr** [comment]
Awesome!
