### ISSUE TITLE
AudioFX doesnt seem to work

### ISSUE THREAD

**Issue by sdevmaster** [visi0nary/android_device_alps_k05ts_a#67]
Dont now if only over bt, or if my headset is simply shit, but it doesnt work. Couldnt install viperfx either (but i think thats a problem of my busybox).

**Comment by janengelmohr** [comment]
https://github.com/visi0nary/android_device_elephone_p8000/issues/63 Possible duplicate?

**Comment by sdevmaster** [comment]
Yes, sorry, tested with poweramp, with preinstalled music app it works perfectly.

**Comment by janengelmohr** [comment]
No problemo ;)
