### ISSUE TITLE
No EAP-SIM

### ISSUE THREAD

**Issue by alancolant** [visi0nary/android_device_alps_k05ts_a#68]
No sim mode in EAP method (wifi).

**Comment by walter79** [comment]
does it work with stock rom?

**Comment by alancolant** [comment]
yes

**Comment by walter79** [comment]
can you post a log?

**Comment by janengelmohr** [comment]
How about now? https://github.com/visi0nary/android_device_elephone_p8000/commit/7d86dc0106228bf34ff4c6bc2c7144fbeb2675de

**Comment by janengelmohr** [comment]
CM 12.1 won't get any new features, so #wontfix
