### ISSUE TITLE
Encryption is broken

### ISSUE THREAD

**Issue by janengelmohr** [visi0nary/android_device_alps_k05ts_a#69]
D/PhoneStatusBar(  846): heads up is disabled
V/WindowManager(  695): Adding window Window{3bcd373d u0 com.android.settings/com.android.settings.CryptKeeperConfirm$Blank} at 6 of 10 (after Window{3403485e u0 com.android.settings/com.android.settings.SubSettings})
D/mali_winsys( 1169): new_window_surface returns 0x3000
I/[MALI][Gralloc](255): Usage: 0xb00, format: 0x1 stride: 1088 vertical_stride: 1920 size: 8355840
D/AudioALSAStreamOut(  281): latency(), return 92
D/GraphicBuffer(  255): alloc, handle(0x7fa6ecfe20) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00) err(0)
I/[MALI][Gralloc](255): Usage: 0xb00, format: 0x1 stride: 1088 vertical_stride: 1920 size: 8355840
D/GraphicBuffer(  255): alloc, handle(0x7fa6ecff60) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00) err(0)
I/[MALI][Gralloc](255): Usage: 0xb00, format: 0x1 stride: 1088 vertical_stride: 1920 size: 8355840
D/GraphicBuffer(  255): alloc, handle(0x7fa6f0e020) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00) err(0)
D/GraphicBuffer( 1169): register, handle(0x7f8d1f7e20) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00)
D/AudioALSAStreamOut(  281): latency(), return 92
I/ActivityManager(  695): Displayed com.android.settings/.CryptKeeperConfirm$Blank: +130ms
D/GraphicBuffer( 1169): register, handle(0x7f8d212520) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00)
D/GraphicBuffer( 1169): unregister, handle(0x7f8d20d9c0) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00)
D/GraphicBuffer( 1169): unregister, handle(0x7f9aad2060) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00)
D/GraphicBuffer( 1169): unregister, handle(0x7f8d129a60) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00)
D/OpenGLRenderer( 1169): endAllStagingAnimators on 0x7f8da81400 (RippleDrawable) with handle 0x7f8d21e0e0
I/Timeline( 1169): Timeline: Activity_idle id: android.os.BinderProxy@27ca5db time:258472
D/GraphicBuffer(  255): free, handle(0x7fa6fa5b00) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00)
D/GraphicBuffer(  255): free, handle(0x7fabc12b60) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00)
D/GraphicBuffer(  255): free, handle(0x7fabc13880) (w:1080 h:1920 s:1088 f:0x1 u:0x000b00)
I/Timeline(  695): Timeline: Activity_windows_visible id: ActivityRecord{575de8 u0 com.android.settings/.CryptKeeperConfirm$Blank t3413} time:258820
D/FrameworkListener(  254): dispatchCommand data = (12 cryptfs enablecrypto inplace pin 323831323931)
E/Cryptfs (  254): Bad magic for real block device /dev/block/platform/mtk-msdc.0/by-name/metadata
D/Cryptfs (  254): Just asked init to shut down class main
D/Cryptfs (  254): unmounting /mnt/shell/emulated succeeded

**Comment by visi0nary** [comment]
/metadata seems to be broken, the question is why? It worked in build 5.

**Comment by janengelmohr** [comment]
Also see http://forum.xda-developers.com/showpost.php?p=66738184&postcount=1021

**Comment by walter79** [comment]
partial fix. Rename /system/lib64/libslos.so  to libslos.old  reboot and start device encryption
This breaks fingerprint.

**Comment by janengelmohr** [comment]
Fixed with https://github.com/visi0nary/android_vendor_elephone_p8000/commit/2746fd76156e70951d01a44a86c92e3015ee1cd1
