### ISSUE TITLE
dt2w cm settings not working

### ISSUE THREAD

**Issue by walter79** [visi0nary/android_device_alps_k05ts_a#71]
You can not switch dt2w on/off inside cm setting.

**Comment by janengelmohr** [comment]
fixed with https://github.com/visi0nary/android_device_elephone_p8000/commit/344814ea13000a03a719a0ee5aae557106fc345c and https://github.com/visi0nary/android_kernel_elephone_p8000/commit/35dbbf8f37cdd74a83a0c9fb954c6ad83641c8a6
