### ISSUE TITLE
Fingerprint not working / Not availble

### ISSUE THREAD

**Issue by mrx-m** [visi0nary/android_device_alps_k05ts_a#77]

**Comment by janengelmohr** [comment]
Works fine for me. The method will stay on PIN and on the lock screen you won't see any animation but it works nevertheless. Those are only visual bugs though.

**Comment by valascus** [comment]
#confirmed

**Comment by janengelmohr** [comment]
So it does not work for you either, @valascus?

**Comment by valascus** [comment]
no, it works xD
confirmed what you said

**Comment by janengelmohr** [comment]
@meow-m Did you apply all the patches when building from source? If not, on which of my unofficial builds are you at the moment?

**Comment by janengelmohr** [comment]
Closed because it works for me and multiple users on XDA

**Comment by adriaade** [comment]
The fingerprint reader does not work for me since the last software upgrade Elephont stock. With this ROM cm-12.1-20160617-UNOFFICIAL-p8000.zip, it does not work I do not detect any trace.
