### ISSUE TITLE
Deliver OTA via https

### ISSUE THREAD

**Issue by janengelmohr** [visi0nary/android_device_alps_k05ts_a#79]

**Comment by janengelmohr** [comment]
Let's encrypt works only on domains, not on IPs. We need to buy a domain I guess

**Comment by skolarianer** [comment]
What about a free certificate from
https://www.startssl.com
?

**Comment by nachfuellbar** [comment]
i could create a subdomain to your url
is your ip fixed?
if you write me a mail i see this quicker than here ;)

**Comment by janengelmohr** [comment]
IP is fixed, yup. Sorry I do not recall your mail adress, could you write me one? :+1:

**Comment by janengelmohr** [comment]
Fixed with b6fa54e2b58b24903fee2f55bb495de784f80841 thanks to @nachfuellbar for the subdomain!
