### ISSUE TITLE
"Double-tap to wake" can't be switched off

### ISSUE THREAD

**Issue by skolarianer** [visi0nary/android_device_alps_k05ts_a#82]
Option "Double-tap to wake" (Display &lights) can't be disabled. If you switch it off, it re-enables itself.

**Comment by walter79** [comment]
it is fixed with this 2 commits:

kernel: https://github.com/visi0nary/android_kernel_elephone_p8000/commit/35dbbf8f37cdd74a83a0c9fb954c6ad83641c8a6

device: https://github.com/visi0nary/android_device_elephone_p8000/commit/344814ea13000a03a719a0ee5aae557106fc345c
