### ISSUE TITLE
Fingerprint sensor doesn't work the first time after restart

### ISSUE THREAD

**Issue by skolarianer** [visi0nary/android_device_alps_k05ts_a#83]
Fingerprint sensor doesn't work the first time after restart. Phone must be unlocked by code.

**Comment by valascus** [comment]
It is suposed to.
On stock rom, it works, but i think that it's a security measure.

**Comment by janengelmohr** [comment]
That's a minor issue anyways and meant as a security measure I guess. Thanks for reporting!
