### ISSUE TITLE
missing camera support for newer p8000

### ISSUE THREAD

**Issue by walter79** [visi0nary/android_device_alps_k05ts_a#86]
Back Camera: ar1335       13 MP Back Cam - [more information](http://www.onsemi.com/PowerSolutions/product.do?id=AR1335)  4K 30fps, 1080P 60fps and 720P 120fps

Front Camera: s5k5e2 Samsung 2560x1920 (5M) - [more information](http://www.samsung.com/semiconductor/products/cmos-image-sensor/mobile-cis/S5K5E2?ia=217) maybe sensor is 180° placed rotated on mainboard

**old P8000**

cat /proc/driver/camera_info

Back Camera: s5k3l2 Samsung 4208x3120 (13M) - [more information](http://www.samsung.com/semiconductor/products/cmos-image-sensor/mobile-cis/S5K3L2?ia=217)

Front Camera: s5k5e2 Samsung 2560x1920 (5M) - [more information](http://www.samsung.com/semiconductor/products/cmos-image-sensor/mobile-cis/S5K5E2?ia=217)

**Comment by janengelmohr** [comment]
Fixed with https://github.com/visi0nary/android_kernel_elephone_p8000/pull/5 and https://github.com/visi0nary/android_vendor_elephone_p8000/commit/a0dedcd478258db66ea5f82471302fbd0f606303
