### ISSUE TITLE
The headphone jack is not working properly

### ISSUE THREAD

**Issue by adriaade** [visi0nary/android_device_alps_k05ts_a#88]
I have tried several headphones and does not work well either, so the FM radio does not work. Connector worked with stock ROM.

**Comment by anibalribeiro** [comment]
Sure that isnt a hardware problem?

**Comment by adriaade** [comment]
I'm not sure, but before changing the Rom, the jack and FM radio worked.
    I have a bad experience in believing that the fault of the hardware. 15 days ago I installed a Elephon P6000pro, the CM 12.1, after not working my mobile USB connector, and could not charge the phone (he was always 1% battery). I took the phone to repair and changed the whole piece usb. The problem was not the harward, it was error of the Rom (BOOT.IMG file).

**Comment by janengelmohr** [comment]
Offline charging is handled by little kernel (lk.bin) as far as I know so charging should still work. Maybe it was just coincidence? Could you flash stock again and see if it works?

**Comment by adriaade** [comment]
Ja As I said, the error was in the boot.img file already is settled at a later Rom. The Elephont P6000pro ha working properly. http://bbs.elephone.hk/thread-9850-1-1.html#.V2kFibgqqhf

   The problem I have in:
    1.) audio jack Elephone P8000 (Rom stock worked fine)
    2.) The fingerprint reader does not work for me since the last software upgrade Elephont stock. With cm-12.1-20160617-UNOFFICIAL-p8000.zip ROM, it does not work I do not detect any trace.

**Comment by janengelmohr** [comment]
/system is completely formatted before the ROM is flashed, so it should not matter on what ROM you were before. Fingerprint works fine for me on 17/06/16 - I tested it this exact moment. Sorry if I repeat myself but did you flash the stock ROM again and checked if headphone jack works there? Thank you for reporting possible bugs by the way! :)

**Comment by adriaade** [comment]
I understand what you say, but Rom stock can only think to flash by SP Tools, you can not by RECOVERY and may lose the IME's. If I decide to flash the stock, I'll post if the fingerprint reader and headphone jack works. Thanks for your interest.

**Comment by janengelmohr** [comment]
Okay :) Just reply here when you flashed stock again. #closed until then

**Comment by olegsvs** [comment]
@visi0nary http://vk.com/away.php?to=http%3A%2F%2Fwww.needrom.com%2Fdownload%2Fs3-cm13-0%2F
cm13 via 3-18 6753

**Comment by olegsvs** [comment]
http://www.needrom.com/download/s3-cm13-0/

**Comment by janengelmohr** [comment]
Yup, I know DerTeufel and we had multiple chats about that device as he is one of the maintainers ;) Thanks for the hint though!

**Comment by olegsvs** [comment]
@visi0nary U use healthd from cm sources with no changes?  I have seen some users jump from 40% to 0 % in the stock kernel. Any ideas?

**Comment by janengelmohr** [comment]
If you refer to the drop, it is a kernel issue alone and has nothing to do with healthd. 
https://github.com/visi0nary/android_kernel_elephone_p8000/commit/c0595d2a5edd631605f12786dc3bf59d4fdc4de5

**Comment by olegsvs** [comment]
@visi0nary me use stock kernel
