### ISSUE TITLE
There's no rotation toggle in the quick pulldown menu

### ISSUE THREAD

**Issue by janengelmohr** [visi0nary/android_device_alps_k05ts_a#9]
Rotation can be disabled via settings though...

**Comment by davidep** [comment]
Confirmed, the option is not there by default and it is not possible to be added later via "Notification Drawer->Select and order tiles" option

**Comment by walter79** [comment]
worked on 20160228 walter79 build

**Comment by walter79** [comment]
fixed with https://github.com/visi0nary/android_device_elephone_p8000/commit/fa1da57391d4ccf26e1ec64edafb39e80b4380cd
