### ISSUE TITLE
Google Photos crash May be due to libstagefright issue

### ISSUE THREAD

**Issue by davidep** [visi0nary/android_device_alps_k05ts_a#94]
At least on a clean CM build 13.09( but this issue is happening since long time.... ) I also opened the issue on google photos forum [url]https://productforums.google.com/forum/#!topic/photos/KQixIMrEszc[/url]

The app is crashing randomly even when it is running in the background.

https://drive.google.com/open?id=0B3F8AHoL8kifTzZDSm91THJEMEk Here some screenshots from the crash report. 
It seems related to lib stagefright and some  codec issues 

09-19 10:43:35.183 E/SQLiteLog(19510): (283) recovered 55 frames from WAL file /data/data/com.google.android.apps.photos/databases/gphotos1.db-wal

09-19 10:43:47.337 D/StagefrightMetadataRetriever(285): Stridewidth=1280,SliceHeight=720
09-19 10:43:53.447 D/FFmpegExtractor(285): unsuppoted codec(ac3) by official Stagefright
09-19 10:43:57.373 W/ActivityManager(735): Scheduling restart of crashed service com.google.android.apps.photos/com.google.android.libraries.social.async.BackgroundTaskService in 1000ms

**Comment by janengelmohr** [comment]
Google Photos app is known to cause problems, though I don't know the exact cause. Other video players (MX,...) work fine though.

**Comment by davidep** [comment]
yes different video players works fine, but is not clear what is making the app crashing even without playing any videos.
I posted several crash and eventlogs [here](https://drive.google.com/drive/folders/0B3F8AHoL8kifTzZDSm91THJEMEk?usp=sharing)

After several full wipe followed by the installation of the last [URL="http://forum.xda-developers.com/index.php"]openGapps [/URL]available, the problem persists: Google photos crash after a while, without any windows popping up anymore to report the crash, as it was happening before the first full wipe. 

I'm wondering if the last Gapps bundle might cause additional problems (last tested was ARM64, micro 20161011), and if so if there is a specific version recommended with the last ROM available (built 20161009)

I see several errors related to SQLlite:
10-12 07:08:27.131 26460 26460 W ResourcesManager: Asset path '/system/framework/android.test.runner.jar' does not exist or contains no resources.
10-12 07:10:08.557   751  1538 I WindowState: WIN DEATH: Window{20004c29 u0 com.google.android.apps.photos/com.google.android.apps.photos.home.HomeActivity}
10-12 07:10:08.576   751  4065 I ActivityManager: Process com.google.android.apps.photos (pid 30311) has died
10-12 07:10:08.579   751  4065 W ActivityManager: Scheduling restart of crashed service com.google.android.apps.photos/com.google.android.libraries.social.async.BackgroundTaskService in 1000ms
10-12 07:44:47.467 29173 29173 E SQLiteLog: (283) recovered 55 frames from WAL file /data/data/com.google.android.calendar/databases/timelydata.db-wal
10-12 08:07:38.295 30609 30609 E SQLiteLog: (283) recovered 36 frames from WAL file /data/user/0/com.android.providers.media/databases/external.db-wal
10-12 08:07:38.342 30609 30630 E SQLiteLog: (283) recovered 83 frames from WAL file /data/user/0/com.android.providers.media/databases/internal.db-wal
10-12 08:08:03.596 26706 30668 E SQLiteLog: (283) recovered 61 frames from WAL file /data/data/com.google.android.apps.photos/databases/disk_cache-wal
10-12 08:08:10.006 26706 30702 E SQLiteLog: (283) recovered 106 frames from WAL file /data/data/com.google.android.apps.photos/databases/gphotos1.db-wal
10-12 08:08:54.215 31028 31054 E SQLiteLog: (283) recovered 19 frames from WAL file /data/data/com.google.android.apps.photos/databases/gphotos0.db-wal
10-12 08:08:54.421 31028 31067 E SQLiteLog: (283) recovered 43 frames from WAL file /data/data/com.google.android.apps.photos/databases/media_store_extras-wal

**Comment by janengelmohr** [comment]
Possibly fixed with https://github.com/visi0nary/android_device_mt6753_common/pull/2
