### ISSUE TITLE
Latest update broke everything

### ISSUE THREAD

**Issue by stefandavcev** [visi0nary/android_device_alps_k05ts_a#97]
This morning I updated my phone to cm-12.1-20161027 and now my phone is randomly freezing whenever I open some app it freezes and I cannot do anything. I have to restart my phone and then everything repeats.

**Comment by janengelmohr** [comment]
Just installed latest nightly, cannot verify. Everything works for 12.1. Do you have a logcat or something? Sounds like a hardware defect tbh

**Comment by stefandavcev** [comment]
how is it a hardware defect if I rolled back to an earlier version and it works perfectly fine?

**Comment by janengelmohr** [comment]
If you provide more infos I will happily look into it

**Comment by stefandavcev** [comment]
Today I tried updating to the latest version and I got the same problem again. What should I provide you with?

**Comment by valascus** [comment]
try to get a logcat until the time it does that and send it or paste it on pastebin or so.

U can check how can it be done here: http://forum.xda-developers.com/showthread.php?t=1726238

Good luck!
